# Generated by Django 3.0.7 on 2020-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
