# Generated by Django 3.0.7 on 2020-07-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200712_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='contact',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
